services:
  # A Docker web service
  - type: web
    name: Movie_Robot
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/Mujju432/Movie_Robot.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
